### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ariona** [godness84/react-native-recyclerview-list#1]
Hello, i want to try this lib but got this error when building:

```terminal
/project_name/node_modules/react-native-recyclerview-list/android/src/main/java/com/github/godness84/RNRecyclerViewList/RecyclerViewBackedScrollView.java:36: error: cannot find symbol
import com.facebook.react.views.scroll.VelocityHelper;
                                      ^
  symbol:   class VelocityHelper
  location: package com.facebook.react.views.scroll
/project_name/node_modules/react-native-recyclerview-list/android/src/main/java/com/github/godness84/RNRecyclerViewList/RecyclerViewBackedScrollView.java:55: error: cannot find symbol
    private final VelocityHelper mVelocityHelper = new VelocityHelper();
                  ^
  symbol:   class VelocityHelper
  location: class RecyclerViewBackedScrollView
/project_name/node_modules/react-native-recyclerview-list/android/src/main/java/com/github/godness84/RNRecyclerViewList/RecyclerViewBackedScrollView.java:55: error: cannot find symbol
    private final VelocityHelper mVelocityHelper = new VelocityHelper();
                                                       ^
  symbol:   class VelocityHelper
  location: class RecyclerViewBackedScrollView
/project_name/node_modules/react-native-recyclerview-list/android/src/main/java/com/github/godness84/RNRecyclerViewList/RecyclerViewBackedScrollView.java:248: error: cannot find symbol
                            mOnScrollDispatchHelper.getXFlingVelocity(),
                                                   ^
  symbol:   method getXFlingVelocity()
  location: variable mOnScrollDispatchHelper of type OnScrollDispatchHelper
/project_name/node_modules/react-native-recyclerview-list/android/src/main/java/com/github/godness84/RNRecyclerViewList/RecyclerViewBackedScrollView.java:249: error: cannot find symbol
                            mOnScrollDispatchHelper.getYFlingVelocity(),
                                                   ^
  symbol:   method getYFlingVelocity()
  location: variable mOnScrollDispatchHelper of type OnScrollDispatchHelper
/project_name/node_modules/react-native-recyclerview-list/android/src/main/java/com/github/godness84/RNRecyclerViewList/RecyclerViewBackedScrollView.java:314: error: method obtain in class ScrollEvent cannot be applied to given types;
                    .dispatchEvent(ScrollEvent.obtain(
                                              ^
  required: int,ScrollEventType,int,int,int,int,int,int
  found: int,ScrollEventType,int,int,int,int,int,int,int,int
  reason: actual and formal argument lists differ in length
/project_name/node_modules/react-native-recyclerview-list/android/src/main/java/com/github/godness84/RNRecyclerViewList/RNRecyclerviewListPackage.java:14: error: RNRecyclerviewListPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNRecyclerviewListPackage implements ReactPackage {
       ^
Note: /project_name/node_modules/react-native-recyclerview-list/android/src/main/java/com/github/godness84/RNRecyclerViewList/RecyclerViewBackedScrollViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
7 errors
```

**Comment by godness84** [comment]
Which version of ReactNative are you using?

**Comment by ariona** [comment]
I use 0.44.0

**Comment by godness84** [comment]
The latest version `0.2.0` is compatible with `RN 0.48.0`.
So you have two options:
- upgrade to `RN 0.48.0` or
- install the `0.1.2` version that is compatible with `RN 0.45.1` (maybe it will still work with `RN 0.44.0`) - launching the `npm i react-native-recyclerview-list@0.1.2 --save` command

**Comment by ariona** [comment]
Upgraded to 0.49 and it's work. But it's kinda slow on development.

And one more thing, Is there any way to add *offset* when using `initialScrollIndex` prop. Since I have sticky navbar (that will visible when user scroll) the item get covered (need to add an offset to it)

**Comment by godness84** [comment]
Is it slower than FlatList in development mode?

At the moment there is no _offset_ parameter. 
If I will have time, I will add it in the next days. Anyway PRs are welcome :)
